CREATE PROCEDURE "3_HANA_HADOOP_IMAGEPROCESSING"."3_HANA_HADOOP_IMAGEPROCESSING::TRUNCATE_TABLES" ( ) 
	LANGUAGE SQLSCRIPT
	SQL SECURITY INVOKER 
	--DEFAULT SCHEMA <default_schema_name>
	--READS SQL DATA AS
	AS
BEGIN
/***************************** 
	Write your procedure logic 
 *****************************/
 	truncate table 3_HANA_HADOOP_IMAGEPROCESSING.PPARAM;
	truncate table 3_HANA_HADOOP_IMAGEPROCESSING.IMG_RES_HANA;
	truncate table 3_HANA_HADOOP_IMAGEPROCESSING.PRED_MODEL_RESULTS_2;
END;
